version: '3.8'

services:
  backend:
    build: .
    command: ['uvicorn', 'src.main:app', '--host', '0.0.0.0', '--port', '8000']
    ports:
      - '8000:8000'
    env_file: .env

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD}'
    volumes:
      - mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_URL: '${MONGO_CONNECTION_STRING}'

volumes:
  mongo:
  redis: